### PR TITLE
Clone App Locally and Update Team Members Section 

### PR DESCRIPTION
**Pull request by ibimina**
Added my name to Team Members section
Issue #4

### CODE REVIEW

**Review by annonymousauthority — APPROVED** [review]

**Comment by msarit** [comment]
@ibimina I changed the destination branch on your PR from `deployment` to `main`. By default, we are cutting all PRs against `main`, unless we create a staging branch in future.

**Comment by msarit** [comment]
Also this is the feature branch naming convention we are adopting:

Start wit your name followed by an underscore: `arit_`
Complete the branch name with a short description of what the PR will do: `arit_update_readme_with_my_name`

**Comment by msarit** [comment]
@ibimina you did not assign yourself to this ticket

**Comment by ibimina** [comment]
Noted

**Pull request closed without merging**
