### PR TITLE
Neka-Update README with my name under Team Members

### LINKED ISSUE #3: Neka - Clone App Locally and Update Team Members Section (SP: 2)
STORY POINTS: 2

### PR DESCRIPTION
**Pull request by istoga**
resolves #3

### CODE REVIEW

**Review by msarit — APPROVED** [review]
Looking good!

**Comment by jjleigh** [comment]
Looks good 👍

**Comment by msarit** [comment]
@istoga Fix the conflicts Neka then I will merge 🙏🏾

**Comment by msarit** [comment]
@istoga Hey Neka, please do not merge PRs. That is just for myself, Augustine or Justine. Thanks! 🙏🏾

**Pull request merged**
