### PR TITLE
Seyi- Styled loginPage using Tailwind

### PR DESCRIPTION
**Pull request by Sheyitofunmi**
## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update
- [ ] Other (please specify here: <type here>)
  
  
## Description of what this Pull Request does
The PR is the login page component styled with tailwind Css

## Related Tickets & Documents
- Closes # ( #32 )
- Related Issues: (#96 )
  
## QA Instructions, Screenshots, Recordings
SignInPage

  
## Added/updated tests?
- [ ] Yes
- [ ] Not Yet, and here is why: __explain here__
- [ ] I need help with tests
- [x] No, and here is why: __explain here__

### CODE REVIEW

**Review by jjleigh — COMMENTED** [review]
It looks good. My only request is that you add a description of the changes to the PR description.

**Comment by Sheyitofunmi** [comment]
thank you @jjleigh will make the changes

**Comment by ibimina** [comment]
@Sheyitofunmi  what route is you login page displayed in?
What I am seeing on my screen is different your the screenshot you post in your pull request?

**Comment by Sheyitofunmi** [comment]
> @Sheyitofunmi what route is you login page displayed in? What I am seeing on my screen is different your the screenshot you post in your pull request? This pull request is closed is there a reason?

the PR is not merged yet, so you may not be able to see the updated version, i do use localhost:3000/login

**Comment by ibimina** [comment]
> > @Sheyitofunmi what route is you login page displayed in? What I am seeing on my screen is different your the screenshot you post in your pull request? This pull request is closed is there a reason?
> 
> 
> 
> the PR is not merged yet, so you may not be able to see the updated version, i do use localhost:3000/login

Ok seen

**Review by annonymousauthority — APPROVED** [review]
Seen

**Review by jjleigh — APPROVED** [review]

**Pull request merged**
