### PR TITLE
36 achele Footer bar component

### PR DESCRIPTION
**Pull request by Achele**
## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Other (please specify here: Component creation)
  
  
## Description of what this Pull Request does
Added a Footer bar component in the common folder of the components folder
- The component makes use of the reusable links to create the navigation links in the footer bar.
- The component also uses the logo component

## Related Tickets & Documents
- Closes # ( #36 )
- Related Issues: (#45 )
  
## QA Instructions, Screenshots, Recordings
FooterBar Component
  
## Added/updated tests?
- [ ] Yes
- [ ] Not Yet, and here is why: __explain here__
- [ ] I need help with tests
- [x] No, and here is why: __explain here__

### CODE REVIEW

**Review by jjleigh — APPROVED** [review]
LGTM 👍

**Comment by ibimina** [comment]
@Achele  your branch is some commits behind main branch, Kindly update your branch

**Review by msarit — APPROVED** [review]
🎉

**Comment by TaylorDJones11** [comment]
@arit this merge created two component folders. We agreed as a team to structure the folders "components/common" .. not just "common"
Screenshot 2023-04-25 at 10 55 45

**Pull request merged**
